# Generated by Django 5.1.4 on 2024-12-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='created_at',
            new_name='posted_on',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='requirements',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.employerprofile'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='Default Location', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(default='Untitled Job', max_length=255),
        ),
    ]
